markdown: kramdown
url: ""
baseurl: null
title: AgileWays
description: Cloud Native and Identity Solutions
site-image: /
site-keywords: "Cloud Native, Identity, Software, Development, Consulting, Success, Solutions"
favicon-url: null
heroimage: http://localhost:4000/IMG-5480.jpg
email: help@agileways.com
facebook_username:
twitter_username: AgileWays
instagram_username:
linkedin_username: /
github_username: AgileWaysLlc
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:
google-analytics:
disqus-shortname:
author-name: AgileWays, LLC
author-image: "https://pbs.twimg.com/profile_images/1647210265669140482/n85_4Hi8_400x400.jpg"
author-about: >-
  AgileWays is a technology consultancy focusing on identity and cloud native app development architectures and solutions.
author-url: "https://github.com/AgileWaysLlc"
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: "blog/:title"
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
